import PDFDocument from "pdfkit"
import fs from "fs"
import path from "path"

export function generatePDF(user, reportData){

  const fileName = `report_${Date.now()}.pdf`
  const filePath = path.join("tmp", fileName)

  // ensure folder exists
  if (!fs.existsSync("tmp")) {
    fs.mkdirSync("tmp")
  }

  const doc = new PDFDocument()

  doc.pipe(fs.createWriteStream(filePath))

  // 🔥 HEADER
  doc
    .fontSize(20)
    .text("HISABI CASH REPORT", { align: "center" })

  doc.moveDown()

  // 🔥 USER INFO
  doc
    .fontSize(12)
    .text(`User: ${user.name || "User"}`)
    .text(`Business: ${user.business_name || "-"}`)
    .text(`Date: ${new Date().toLocaleDateString()}`)

  doc.moveDown()

  // 🔥 FINANCIAL DATA
  doc
    .fontSize(14)
    .text("FINANCIAL SUMMARY", { underline: true })

  doc.moveDown()

  doc
    .fontSize(12)
    .text(`Total Sales: Rs ${reportData.sales}`)
    .text(`Total Expense: Rs ${reportData.expense}`)
    .text(`Udhar Given: Rs ${reportData.udhar}`)
    .text(`Net Profit: Rs ${reportData.profit}`)

  doc.moveDown()

  // 🔥 FOOTER
  doc
    .fontSize(10)
    .text("Generated by Hisabi Cash AI", { align: "center" })

  doc.end()

  return filePath
}